kind: configuration
hooks:
   postmonitor:
     tgrflow:
       library location: /home/tomasz.baka/asimov_testing/cbc-workflow-o4a
   applicator:
     tgrflow:
       library location: /home/tomasz.baka/asimov_testing/cbc-workflow-o4a
data:
  channels:
    H1: H1:GDS-CALIB_STRAIN_CLEAN
    L1: L1:GDS-CALIB_STRAIN_CLEAN
    V1: V1:Hrec_hoft_16384Hz
  frame types:
    H1: H1_HOFT_C00
    L1: L1_HOFT_C00
    V1: V1Online
pipelines:
  gwdata:
    scheduler:
      accounting group: ligo.prod.o4.cbc.testgr.tiger
      request cpus: 1
  peconfigurator:
    scheduler:
      accounting group: ligo.prod.o4.cbc.testgr.tiger
      request cpus: 1
  bilbymdr:
#    template: template_file (I think this is the right place for non default template)
    tgr schema section: MDRAnalyses
    quality:
      state vector:
        L1: L1:GDS-CALIB_STRAIN_CLEAN
        H1: H1:GDS-CALIB_STRAIN_CLEAN
        V1: V1:Hrec_hoft_16384Hz
    sampler:
      sampler: dynesty
      parallel jobs: 3
    scheduler:
      accounting group: ligo.prod.o4.cbc.testgr.tiger
      request cpus: 16
      request disk: 8
    likelihood:
      frequency domain source model: bilby_tgr.mdr.source.lal_binary_black_hole
      marginalization:
          distance: False
    waveform:
      approximant: IMRPhenomXPHM
      generation function: bilby_tgr.mdr.conversion.generate_all_bbh_parameters
  bayeswave:
    quality:
      state vector:
        L1: L1:GDS-CALIB_STRAIN_CLEAN
        H1: H1:GDS-CALIB_STRAIN_CLEAN
        V1: V1:Hrec_hoft_16384Hz
    scheduler:
      accounting group: ligo.prod.o4.cbc.testgr.tiger
      request memory: 1024
      request post memory: 16384
    likelihood:
      iterations: 100000
      chains: 8
      threads: 4
postprocessing:
  pesummary:
    accounting group: ligo.prod.o4.cbc.testgr.tiger
    cosmology: Planck15_lal
    evolve spins: forwards
    multiprocess: 4
    redshift: exact
    regenerate posteriors:
    - redshift
    - mass_1_source
    - mass_2_source
    - chirp_mass_source
    - total_mass_source
    - final_mass_source
    - final_mass_source_non_evolved
    - radiated_energy
    skymap samples: 2000
quality:
  minimum frequency:
    H1: 20
    L1: 20
    V1: 20
    G1: 20
    K1: 20
priors:
    amplitude order: 2
    chirp mass:
        maximum: 100
        minimum: 0
        type: bilby.gw.prior.UniformInComponentsChirpMass
    dec:
        type: Cosine
    luminosity distance:
        alpha: 2
        maximum: 1000
        minimum: 10
        type: PowerLaw
    mass 1:
        maximum: 1000
        minimum: 1
        type: Constraint
    mass 2:
        maximum: 1000
        minimum: 1
        type: Constraint
    mass ratio:
        maximum: 1.0
        minimum: 0.1
        type: bilby.gw.prior.UniformInComponentsMassRatio
    phase:
        boundary: periodic
        type: Uniform
    phi 12:
        type: Uniform
    phi jl:
        type: Uniform
    psi:
        type: Uniform
    ra:
        type: Uniform
    spin 1:
        maximum: 1
        minimum: 0
        type: Uniform
    spin 2:
        maximum: 1
        minimum: 0
        type: Uniform
    theta jn:
        type: Sine
    tilt 1:
        type: Sine
    tilt 2:
        type: Sine
